"""Initial migration

Revision ID: 178b97f0db95
Revises: 
Create Date: 2024-12-16 22:39:20.233883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178b97f0db95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('id_brand', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('properties', sa.String(length=40), nullable=True),
    sa.Column('taste', sa.String(length=30), nullable=True),
    sa.Column('appearance', sa.String(length=50), nullable=True),
    sa.Column('id_province', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_brand'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['id_province'], ['province.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id_category', 'id_product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category')
    op.drop_table('product')
    op.drop_table('province')
    op.drop_table('brand')
    op.drop_table('product_type')
    op.drop_table('country')
    op.drop_table('category')
    # ### end Alembic commands ###
